---
title: "Project3McGuire Package Vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Project3McGuire Package Vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(Project3McGuire)
```

```{r Demonstrate Exp Function, fig.width=8, fig.height=6}
library(ggplot2)
# The Exp Function approximates a Taylor series for a particular number, x, and the number of terms k.
# The plot below shows the value returned by the function as the value of k increases.
# This value eventually approaches the value given by the default function, exp.

# First creates a numeric vector, and then fills the vector with the results of the loop
exp_results <- numeric()
for(i in 1:20) {
  exp_results[[i]] <- Exp(10, i)
}

# Generates the x values for plotting
number_of_terms <- 1:20

# Creates a data frame from the vectors
exp_graphing <- data.frame(exp_results, number_of_terms)

# Plots the dataframe
ggplot(exp_graphing, aes(x = number_of_terms, y = exp_results)) + 
  geom_point() + 
  geom_line(y = 22026.47) +
  labs(title = "Value of the Exp Function at x = 10 and Varying Levels of K", subtitle = "The horizontal line in the image depicts the value of the base function exp(10), 22,026.47") +
  xlab("Value of Parameter K") +
  ylab("Value returned by Exp function") +
  theme_bw()

exp(10)
```


```{r Load in Data}
library(here)
library(tidyverse)

# tests if a directory named "data" exists locally
if(!dir.exists(here("data"))) { dir.create(here("data")) }

# saves data only once (not each time you knit a R Markdown)
if(!file.exists(here("data","chopped.RDS"))) {
  url_tsv <- 'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-25/chopped.tsv'
  chopped <- readr::read_tsv(url_tsv)
  
  # save the file to RDS objects
  saveRDS(chopped, file= here("data","chopped.RDS"))
}
# Reads in the data downloaded earlier
chopped <- readRDS(here("data","chopped.RDS"))
as_tibble(chopped)
```

```{r Remove Missing, Search for Halloween}


# Removes rows missing either episodes notes or ratings
chopped_no_missing <- chopped %>%
  na.omit(episode_notes, episode_rating) 

# Searches the episodes notes column for the phrase alloween, which should search for both upper and lowercase of Halloween
chopped_regex <- chopped_no_missing %>%
  mutate(has_halloween_theme = grepl("alloween", episode_notes))
```

```{r Create Box Plot, fig.width=8,fig.height=6}
# Creates the base 
chopped_box <- ggplot(chopped_regex, aes(x = has_halloween_theme, y = episode_rating, fill = has_halloween_theme))

# Generates the rest of the graph
chopped_box + 
  geom_boxplot() + 
  geom_jitter() +
  labs(title = "Boxplot of 'Chopped' Episode Ratings Comparing Halloween Episodes to non-Halloween Episodes",
       subtitle = "Halloween Episodes N = 7, Non-Halloween Episodes N = 345", fill = "Halloween Theme", caption = "Collin McGuire") +
  xlab("Halloween Theme T/F") +
  ylab("Episode Rating (Scale 0-10)") +
  scale_x_discrete(breaks=c("FALSE", "TRUE"),
                   labels=c("Not Halloween", "Halloween")) +
  scale_fill_discrete(labels = c("Not Halloween", "Halloween"))
```

Looking at the two plots, Halloween episodes have an almost identical median rating as non-Halloween episodes, although the IQR for the Halloween episodes is much larger in a negative manner than that of the non-Halloween Episodes. 

```{r 90% CI for Halloween/Not Halloween Episdoe Ratings}
# Limits the dataset to only episodes with a halloween theme
halloween_true <- chopped_regex %>%
  filter(has_halloween_theme == TRUE)

# Creates a vector from the episode rating column
halloween_vec <- halloween_true$episode_rating

# Makes the vector p3_class
halloween_p3 <- make_p3_class(halloween_vec)

# Double check that the vector is of the p3 class
class(halloween_p3)

# Calculate the CI for the mean of the vector
calculate_CI(halloween_p3,0.90, S3 = TRUE)

# Limits the dataset to only those episodes without a halloween theme
halloween_false <- chopped_regex %>%
  filter(has_halloween_theme == FALSE)

# Creates a vector from the episode rating column
not_halloween_vec <- halloween_false$episode_rating

# Makes the vector p3_class
not_halloween_p3 <- make_p3_class(not_halloween_vec)

# Double checks the vector is p3_class
class(not_halloween_p3)

# Calculate the CI for the mean of the vector
calculate_CI(not_halloween_p3, 0.90, S3 = TRUE)
```

